const cities = [
    "Indore",
    "Mumbai",
    "Bhopal",
    "New Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Jaipur",
    "Ahmedabad",
    "Surat",
    "Nagpur",
    "Lucknow",
    "Kanpur",
    "Patna",
    "Ranchi",
    "Raipur",
    "Chandigarh",
    "Amritsar",
    "Ludhiana",
    "Jodhpur",
    "Varanasi",
    "Agra",
    "New York",
    "Los Angeles",
    "Toronto",
    "Vancouver",
    "London",
    "Manchester",
    "Paris",
    "Berlin",
    "Rome",
    "Madrid",
    "Amsterdam",
    "Zurich",
    "Sydney",
    "Melbourne",
    "Tokyo",
    "Seoul",
    "Beijing",
    "Bangkok",
    "Singapore",
    "Dubai",
    "Cape Town",
    "Cairo",
    "São Paulo",
    "Buenos Aires",
    "Mexico City",
    "Moscow",
    "Istanbul",
    "Abu Dhabi",
    "Doha",
    "Kuwait City",
    "Manama",
    "Muscat",
    "Riyadh",
    "Tehran",
    "Baghdad",
    "Jerusalem",
    "Ankara",
    "Hanoi",
    "Ho Chi Minh City",
    "Jakarta",
    "Kuala Lumpur",
    "Manila",
    "Colombo",
    "Kathmandu",
    "Dhaka",
    "Karachi",
    "Lahore",
    "Islamabad",
    "Tashkent",
    "Astana",
    "Ulaanbaatar",
    "Nairobi",
    "Lagos",
    "Accra",
    "Algiers",
    "Addis Ababa",
    "Casablanca",
    "Tunis",
    "Helsinki",
    "Stockholm",
    "Oslo",
    "Copenhagen",
    "Vienna",
    "Prague",
    "Budapest",
    "Warsaw",
    "Brussels",
    "Athens",
    "Lisbon",
    "Dublin",
    "Reykjavik",
    "Wellington",
    "Auckland",
    "Lima",
    "Santiago",
    "Caracas",
    "Bogotá",
    "Panama City"
];
